Update master.yml

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -60,9 +60,14 @@ jobs:
         run: |
           git config --local user.email "tassinari.leonardo.2000@gmail.com"
           git config --local user.name "Leonardo Tassinari"
-          git diff --exit-code || exit 0  # Exit if there are no changes
-          git add .
-          git commit -m "Generate UML (${{ github.workflow }})"
-          git push origin HEAD:master
+          git diff --exit-code > /dev/null 2>&1  # Suppress output and capture exit code
+          DIFF_EXIT_CODE=$?
+          if [ $DIFF_EXIT_CODE -eq 1 ]; then
+            git add .
+            git commit -m "Generate UML (${{ github.workflow }})"
+            git push origin HEAD:master
+          else
+            echo "No changes to commit."
+          fi
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
